spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/curd_operation
    username: anandmohan
    password: Accenture@123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true